### ISSUE TITLE
quotation marks aren't escaped

### ISSUE THREAD

**Issue by GitNether** [festino-mc-plugins/ClickableLinks#5]
Basically, when you have a message where a link is being replaced and there are quotation marks in any of the blocks, it escapes the string and causes an error (message is then never sent). 

```
20.04 19:24:49 [Server] [INFO] [ClickableLinks] Sending raw JSON: [{"text":""},{"color":"#ffaa00","text":"ยงrยงl<"},{"color":"#ffb728","text":"ยงrยงlI"},{"color":"#ffc550","text":"ยงrยงlV"},{"color":"#ffd278","text":"ยงrยงl>"},{"text":"ยงr "},{"color":"#ffff98","text":"ยงrยงl["},{"color":"#f5e678","text":"ยงr#"},{"color":"#eccc59","text":"ยงr1"},{"color":"#e2b339","text":"ยงrยงl๐"},{"color":"#d89919","text":"ยงrยงl] "},{"text":"ยงrCHMarcell "},{"text":"ยง7โฃ"},{"text":"ยงf "},[{"text":""},{"text":"ยงfshould "},{"text":"ยงfยงnvirtued.pro","clickEvent":{"action":"open_url","value":"https://virtued.pro"}},{"text":"ยงf redirect me to a "Website Expired" page?"}]]
```

Last block is what I mentioned.

Cheers :)

**Comment by festino** [comment]
Thanks for the bug report! I started a big refactoring a month ago and then got busy... Hopefully I can finish the refactoring and fix this issue by the end of the month.

**Comment by festino** [comment]
Update: work in progress, hopefully a new version will be released by the end of the week. It will include clickable commands and a fix for this issue.

**Comment by GitNether** [comment]
Sounds awesome 👀

**Comment by festino** [comment]
Update: refactoring is complete, clickable commands are working (and are being validated against server commands list). I only need to add clickable text (for commands with arguments) and some configuration. May be tomorrow.
