### ISSUE TITLE
ChatHandler ignores event cancellation

### ISSUE THREAD

**Issue by GitNether** [festino-mc-plugins/ClickableLinks#6]
it clashes with our other plugins

Also being able to toggle if IPs should be clickable would be nice

**Comment by festino** [comment]
Could you give an example of how I might encounter the issue with other plugins?

**Comment by GitNether** [comment]
ChatFilter plugin cancels the IPs due to ip leak filter, but the plugin makes them clickable and sends them again because the priority is faulty id guess

**Comment by festino** [comment]
I'll soon see what the conflict is between ChatFilter and ClickableLinks, and maybe add a priority setting. For now I just added `clickablelinks.use.iplinks` permission and `enable-ip-links` configuration option:
https://github.com/festino-mc-plugins/ClickableLinks/releases/tag/v2.0.2

**Comment by festino** [comment]
I found that in ChatHandler I did not check if event was cancelled :D
Fixed in new release: https://github.com/festino-mc-plugins/ClickableLinks/releases/tag/v2.0.3

**Comment by festino** [comment]
Open a new issue if the editable event priority is really necessary.
